name = "nylon"
version = "0.0.1"
description = "Sockets and networking for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "digitalcora", repo = "nylon" }

internal_modules = ["nylon/lib/*"]

[dependencies]
gleam_erlang = "~> 0.18.0"
gleam_stdlib = "~> 0.29.0"

[dev-dependencies]
gleeunit = "~> 0.10.0"
